### ISSUE TITLE
Additional applications: standups and AirMo

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/sso-dashboard-configuration#12]
Can we add the following two apps (RPs) which are using Mozilla's Auth0 authentication:
* standups (https://www.standu.ps)
* Air Mozilla

**Comment by m-branson** [comment]
@comzeradd I've added app icons for standup, air mozilla and bugzilla into the [app-icons folder](https://drive.google.com/open?id=0B0vmiicLLrGuU1BNVTg0aWtLMkU).

(I know @hmitsch didn't ask for bugzilla yet, but just in case it comes up!)

**Comment by andrewkrug** [comment]
@hmitsch looks like AirMo was added but not the standups app.  Should we still add the standups app?

**Comment by hmitsch** [comment]
@andrewkrug can we add StandUps and Bugzilla? Would you be able to do that?

**Comment by gdestuynder** [comment]
these are definitely not in - bugzilla should probably be added

**Comment by gdestuynder** [comment]
dupe: https://github.com/mozilla-iam/sso-dashboard-configuration/issues/25

yes, that means no standup, but i dont see it used anywhere anymore and bug is years old
