### ISSUE TITLE
Cannot login to sso dashboard with github 2fa

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard-configuration#132]
I'm using this email for testing in sso.mozilla.com: moz.parsys@gmail.com - github + 2fa.
Yesterday I managed to login successfully, today I'm getting 500 Internal Server Error. (tried in private browsing also). 
@gdestuynder , any idea what the issue might be?

**Comment by andrewkrug** [comment]
@viorelaioia can you please try again.  I could not replicate this error.

**Comment by andrewkrug** [comment]
Fixed in the last merge.
