### ISSUE TITLE
Not sorted alphabetically

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-iam/sso-dashboard-configuration#165]
Is there a reason why the dashboard apps are not sorted alphabetically? If not, I'm happy to provide a PR that sorts them correctly.

**Comment by m-branson** [comment]
This (alphabetical sorting) was part of initial UX design direction, not quite sure where it fell off. I'm curious how they are sorted currently?

**Comment by MichaelKohler** [comment]
Without checking every entry, I'd say it's sorted up to here: https://github.com/mozilla-iam/sso-dashboard-configuration/blob/master/apps.yml#L746

So the last few entries (probably new ones) are not sorted.

<img width="1070" alt="screen shot 2018-07-19 at 00 49 18" src="https://user-images.githubusercontent.com/330324/42912017-9682a4d0-8aed-11e8-955c-83559eb829be.png">

So you agree a PR for this makes sense?

**Comment by m-branson** [comment]
It does to me, definitely an @hmitsch call though.

**Comment by andrewkrug** [comment]
We did this a long time ago.  Somehow this issue ended up on the wrong repo.
