### ISSUE TITLE
Session handling may be wrong

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/sso-dashboard-configuration#18]
I visited the dashboard, used it for a minute, closed the tab, then browsed again to sso.mozilla.com about 5 to 15 minutes later and was presented with the Auth0 lock asking to confirm my identity.

I would have expected to only be prompted to indicate my identity after some longer window of time, 5 minutes feels like it should be the same session and the RP should assume the user intends to use the same identity.

**Comment by gdestuynder** [comment]
The cookie i get from sso.mozilla.org is indeed 15min

**Comment by gdestuynder** [comment]
we made this 24h for now https://github.com/mozilla-iam/sso-dashboard/pull/106

**Comment by gene1wood** [comment]
This is being worked on in mozilla-iam/sso-dashboard#107
