### ISSUE TITLE
Workday returns error page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard-configuration#20]
When logging into Workday with my ldap (vioia@mozilla.com) through sso dashboard, I'm getting an error page. Should I not have access to workday? 
![workday](https://cloud.githubusercontent.com/assets/5293100/25626387/0c748f10-2f68-11e7-842f-b60e3ee4ab41.png)

**Comment by gdestuynder** [comment]
i believe thats fixed
