### ISSUE TITLE
dashboard shouldn't show services that i don't have access to (plansource)

### ISSUE THREAD

**Issue by globau** [mozilla-iam/sso-dashboard-configuration#21]
recreated here from https://github.com/mozilla-iam/sso-dashboard/issues/99

the new sso dashboard lists plansource which i don't appear to have access to (i guess it's US only?).

"Employee is not found by subscriber code 'bjones@mozilla.com'."

the dashboard shouldn't list items that i cannot access.

**Comment by andrewkrug** [comment]
@globau this is currently not region aware.  I'm going to wontfix this bug until we have the ability to know your region as an employee based on assertions.
