### ISSUE TITLE
Cannot login to discourse from sso dashboard if the ldap is not associated with a discourse account

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard-configuration#22]
**Steps:** 

1. Login to sso dashboard with an LDAP that doesn't have a discourse account associated;
2. Click Discourse app;
2. Enter the same LDAP credentials used in step 1;

**Expected:** Discourse register form is displayed;
**Actual:** Discourse homepage is displayed, user is not logged in. 

**Note:** If trying to login to mozillians with an LDAP that doesn't have a mozillians account associated, mozillians register page is shown, as expected.

**Comment by gdestuynder** [comment]
not relevant to the dashboard, but also i suspect this is no longer an issue
