### ISSUE TITLE
User remains logged in to The Hub after logging out from both The Hub and SSO dashboard

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard-configuration#23]
**Steps:**

1. Login to SSO dashboard;
2. Click The Hub app;
3. Log in to The Hub app;
4. On The Hub homepage click username (top-right), then click Logout button ("Mozilla SSO Log Out Success" message is shown);
5. Close the current tab;
6. On SSO dashboard page, click username, then Logout button ("Mozilla SSO Log Out Success" message is shown);
7. On the current page, click Need Help link shown in the footer;

**Expected:** User should be presented the login form, as he/she previously logged out from the Hub and SSO dashboard;
**Actual:** User is automatically logged into The Hub with the LDAP credentials used in step 3, even though he/she previously performed a log out from both The Hub and SSO dashboard.

**Comment by andrewkrug** [comment]
@viorelaioia is this still an issue?  If so we should move it out of this repository since session handling is the job of the RP

**Comment by viorelaioia** [comment]
This issue is not happening anymore. Closing the ticket.
