### ISSUE TITLE
User can access Egencia account by url, after logging out from both Egencia and SSO dashboard 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard-configuration#24]
**Steps:**
 
1. Login to sso dashboard;
2. Click Egencia and Login to Egencia;
3. Logout from Egencia;
4. Logout from sso dashboard;
5. Navigate to https://www.egencia.com/pub/agent.dll;

**Expected:** Egencia login form is shown
**Actual:** User is automatically logged in to Egencia

**Note:** Same issue happens with Mana and The Hub.

**Comment by gdestuynder** [comment]
this is due to the egencia session, not the sso dashboard
same for all apps

this is why it says when you logout to "log out from each app"

currently, this is the best we have for this, though some app will eventually get this kind of signal forwarded and consumed
