### ISSUE TITLE
Add Salesforce tile for Mozilla Foundation users

### ISSUE THREAD

**Issue by jlin** [mozilla-iam/sso-dashboard-configuration#489]
Filing this on behalf of Jackie Lu @jackielu And Stephanie McVicker

Hi,

Foundation staff uses SSO to access their Salesforce instance and I'd like to get to either get a user friendly url similar to what we used to have or a tile on the SSO Dashboard in order to make on-boarding easier.

Previous URL: http://sso.mozilla.com/salescloud
Current URL: --- (jlin can provide it for you privately or can post if it's ok to post publicly)
Proposed URL: http://sso.mozilla.com/nonprofitcloud

Thanks for your help,

-Steph

@jackielu should be able to provide more context

**Comment by sciurus** [comment]
Hi @jlin ,

It would help us track them better if all requests for

1) New SSO integrations
2) Modifications to existing SSO integrations

were filed at [Infrastructure & Operations, SSO: Requests](https://bugzilla.mozilla.org/buglist.cgi?product=Infrastructure%20%26%20Operations&component=SSO%3A%20Requests&resolution=---&) in Bugzilla. list_id=15780903

I went ahead and move this to https://bugzilla.mozilla.org/show_bug.cgi?id=1722018 for you.
