### ISSUE TITLE
Add a vanity url for Smartling

### ISSUE THREAD

**Issue by marcin-kozinski** [mozilla-iam/sso-dashboard-configuration#845]
I'd like to add a vanity url for Smartling, e.g. `/smartling`.

Happy to send a PR for this, I think I understand how to do it. Just trying to be a good citizen and ask about it in an issue first, to see if that's ok or if maybe there's a reason we didn't/shouldn't/can't do it. Thanks!

**Comment by vansterzzz** [comment]
done.
